import { useState, useEffect } from 'react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Volume2, Wifi, WifiOff, AlertTriangle, RotateCcw, Server } from 'lucide-react';

interface NodeStatus {
  name: string;
  stake: number;
  lastFinalizedSlot: number;
  timeoutSec: number;
  missedWindows: number;
  status: 'online' | 'partitioned' | 'syncing';
}

export default function MegaphoneSimulator() {
  const [nodes, setNodes] = useState<NodeStatus[]>([
    { name: 'Node Zurich', stake: 35, lastFinalizedSlot: 500, timeoutSec: 1.2, missedWindows: 0, status: 'online' },
    { name: 'Node Tokyo', stake: 25, lastFinalizedSlot: 500, timeoutSec: 1.2, missedWindows: 0, status: 'online' },
    { name: 'Node Chicago', stake: 20, lastFinalizedSlot: 500, timeoutSec: 1.2, missedWindows: 0, status: 'online' },
    { name: 'Node Sydney', stake: 12, lastFinalizedSlot: 498, timeoutSec: 1.2, missedWindows: 0, status: 'online' },
    { name: 'Node Frankfurt', stake: 8, lastFinalizedSlot: 500, timeoutSec: 1.2, missedWindows: 0, status: 'online' },
  ]);

  const [networkState, setNetworkState] = useState<'normal' | 'partitioned' | 'recovering'>('normal');
  const [standstillTimer, setStandstillTimer] = useState(0); // seconds since last finalization
  const [simulationLogs, setSimulationLogs] = useState<string[]>(["Network initialized. Consensus running at base 1.2s timeouts."]);

  const addLog = (msg: string) => {
    setSimulationLogs(prev => [msg, ...prev.slice(0, 15)]);
  };

  // Timer loop representing slots progressing
  useEffect(() => {
    let interval: any;
    
    if (networkState === 'normal') {
      // Normal state: progress slots quickly every 1.5s
      interval = setInterval(() => {
        setNodes(prev => prev.map(node => {
          if (node.status === 'online') {
            const nextSlot = Math.max(node.lastFinalizedSlot + 1, 501);
            return {
              ...node,
              lastFinalizedSlot: nextSlot,
              timeoutSec: 1.2,
              missedWindows: 0
            };
          }
          return node;
        }));
        
        // Add log occasionally
        const randomNode = nodes[Math.floor(Math.random() * nodes.length)].name;
        addLog(`Slot finalized successfully. Certificate generated by leader ${randomNode}.`);
      }, 1500);
    } else if (networkState === 'partitioned') {
      // Partitioned state: finalization freezes, clocks tick up
      interval = setInterval(() => {
        setStandstillTimer(t => {
          const nextTime = t + 1;
          
          // Exponential timeout growth if we miss slots/windows
          if (nextTime % 2 === 0) {
            setNodes(prevNodes => prevNodes.map(node => {
              const nextMissed = node.missedWindows + 1;
              const nextTimeout = 1.2 * Math.pow(1.05, nextMissed);
              return {
                ...node,
                missedWindows: nextMissed,
                timeoutSec: parseFloat(nextTimeout.toFixed(2))
              };
            }));
            addLog(`Slot missed! Standstill active. Validators increasing timeouts to offset latency.`);
          }
          
          if (nextTime === 10) {
            addLog(`⚠️ Standstill Trigger reached (10s)! Megaphone Protocol is now armed.`);
          }
          
          return nextTime;
        });
      }, 1000);
    }

    return () => clearInterval(interval);
  }, [networkState, nodes]);

  // Triggers the partition
  const triggerPartition = () => {
    setNetworkState('partitioned');
    setStandstillTimer(0);
    setNodes(prev => prev.map((node, idx) => {
      // Let's divide nodes into two partitioned halves
      if (idx < 3) {
        return { ...node, status: 'partitioned' };
      } else {
        return { ...node, status: 'partitioned' };
      }
    }));
    addLog("🚨 Network Partition Triggered! Global fiber cut simulated. Finalization frozen.");
  };

  // Triggers megaphone recovery
  const triggerMegaphone = () => {
    if (standstillTimer < 10) return;
    setNetworkState('recovering');
    addLog("📢 Validators activated Megaphone broadcast! Sending highest finalization certificates...");

    setTimeout(() => {
      // Sync all nodes to the highest slot seen in the network (e.g. 500)
      setNodes(prev => prev.map(node => ({
        ...node,
        lastFinalizedSlot: 500,
        timeoutSec: 1.2,
        missedWindows: 0,
        status: 'online'
      })));
      setStandstillTimer(0);
      setNetworkState('normal');
      addLog("✅ Network synced successfully! Timeouts snapped back to base 1.2s. Consensus recovered.");
    }, 2000);
  };

  // Reset simulator
  const resetSimulator = () => {
    setNodes([
      { name: 'Node Zurich', stake: 35, lastFinalizedSlot: 500, timeoutSec: 1.2, missedWindows: 0, status: 'online' },
      { name: 'Node Tokyo', stake: 25, lastFinalizedSlot: 500, timeoutSec: 1.2, missedWindows: 0, status: 'online' },
      { name: 'Node Chicago', stake: 20, lastFinalizedSlot: 500, timeoutSec: 1.2, missedWindows: 0, status: 'online' },
      { name: 'Node Sydney', stake: 12, lastFinalizedSlot: 498, timeoutSec: 1.2, missedWindows: 0, status: 'online' },
      { name: 'Node Frankfurt', stake: 8, lastFinalizedSlot: 500, timeoutSec: 1.2, missedWindows: 0, status: 'online' },
    ]);
    setNetworkState('normal');
    setStandstillTimer(0);
    setSimulationLogs(["Network reset. Consensus running at base 1.2s timeouts."]);
  };

  return (
    <div className="space-y-8 animate-fade-in text-left">
      <div className="flex flex-col space-y-2">
        <Badge variant="outline" className="w-fit text-purple-600 border-purple-300 bg-purple-50 dark:bg-purple-950/20 text-sm py-1 px-3">
          Simulator 5: Recovery
        </Badge>
        <h1 className="text-4xl font-extrabold tracking-tight text-slate-900 dark:text-slate-50">
          Megaphone & Timeout Recovery
        </h1>
        <p className="text-lg text-muted-foreground">
          Simulate a catastrophic network outage and trigger the Alpenglow Standstill Megaphone recovery.
        </p>
      </div>

      {/* Control Card */}
      <Card className="border-slate-200 dark:border-slate-800 shadow-sm">
        <CardHeader className="pb-3">
          <CardTitle className="text-xl font-bold flex items-center gap-2">
            <Volume2 className="h-5 w-5 text-purple-600" /> Simulator Dashboard
          </CardTitle>
          <CardDescription className="text-sm">
            Simulate a split network partition, watch local timeouts grow, and use the Megaphone protocol to unfreeze consensus.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Action Buttons */}
          <div className="flex flex-wrap gap-2.5">
            {networkState === 'normal' && (
              <Button onClick={triggerPartition} className="bg-rose-600 hover:bg-rose-700 text-white font-semibold flex items-center gap-1.5 text-sm py-2 px-4 h-auto">
                <WifiOff className="h-4 w-4" /> Simulate Network Partition
              </Button>
            )}
            
            {networkState === 'partitioned' && (
              <Button 
                onClick={triggerMegaphone} 
                disabled={standstillTimer < 10}
                className={`${
                  standstillTimer >= 10 
                    ? "bg-purple-600 hover:bg-purple-700 text-white animate-pulse" 
                    : "bg-slate-300 dark:bg-slate-800 text-slate-500 cursor-not-allowed"
                } font-semibold flex items-center gap-1.5 text-sm py-2 px-4 h-auto`}
              >
                <Volume2 className="h-4 w-4" /> Shout Megaphone Recovery {standstillTimer < 10 && `(Wait ${10 - standstillTimer}s)`}
              </Button>
            )}

            <Button onClick={resetSimulator} variant="outline" className="font-semibold text-sm py-2 px-4 h-auto flex items-center gap-1.5">
              <RotateCcw className="h-4 w-4" /> Reset Simulation
            </Button>
          </div>

          {/* Network Status Header */}
          <div className="p-4 border rounded-lg flex items-center justify-between bg-slate-50 dark:bg-slate-900/50">
            <div>
              <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block">Global Consensus State</span>
              <span className={`text-lg font-bold ${
                networkState === 'normal' ? 'text-emerald-600 dark:text-emerald-400' : 'text-rose-500'
              }`}>
                {networkState === 'normal' && '🟢 Consensus Finalizing (Fast Path)'}
                {networkState === 'partitioned' && `🔴 Standstill Active (${standstillTimer}s elapsed)`}
                {networkState === 'recovering' && '🟡 Megaphone Flooding & Resyncing...'}
              </span>
            </div>
            {networkState === 'partitioned' && standstillTimer >= 10 && (
              <Badge className="bg-purple-600 text-white text-xs uppercase tracking-wider animate-bounce">
                Megaphone Armed
              </Badge>
            )}
          </div>

          {/* Nodes Grid */}
          <div className="grid gap-4 md:grid-cols-5">
            {nodes.map((node, idx) => (
              <Card key={idx} className="border bg-slate-50/50 dark:bg-slate-950/20 text-center p-4 relative overflow-hidden">
                {/* Node visual link status */}
                <div className={`absolute top-2 right-2 ${
                  node.status === 'online' ? 'text-emerald-500' : 'text-rose-500'
                }`}>
                  {node.status === 'online' ? <Wifi className="h-4 w-4" /> : <WifiOff className="h-4 w-4" />}
                </div>

                <Server className={`h-8 w-8 mx-auto mb-2 ${
                  networkState === 'normal' ? 'text-purple-600 dark:text-purple-400 animate-pulse' : 'text-slate-400'
                }`} />

                <h4 className="font-bold text-sm text-slate-800 dark:text-slate-200">{node.name}</h4>
                <span className="text-xs text-muted-foreground block mb-2">{node.stake}% Stake</span>

                <div className="space-y-1.5 border-t pt-2 mt-2 text-xs">
                  <div className="flex justify-between">
                    <span className="text-slate-400">Last Slot:</span>
                    <span className="font-semibold text-slate-700 dark:text-slate-300">{node.lastFinalizedSlot}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Timeout:</span>
                    <span className={`font-mono font-bold ${node.timeoutSec > 1.2 ? 'text-rose-500' : 'text-slate-700 dark:text-slate-300'}`}>
                      {node.timeoutSec}s
                    </span>
                  </div>
                </div>
              </Card>
            ))}
          </div>

          {/* Explanatory visual block */}
          {networkState === 'partitioned' && (
            <div className="p-4 border border-amber-200 bg-amber-50/15 dark:bg-amber-950/5 rounded-lg flex gap-3 items-start animate-fade-in text-sm text-slate-700 dark:text-slate-300">
              <AlertTriangle className="h-5 w-5 text-amber-500 shrink-0 mt-0.5" />
              <div className="space-y-1.5">
                <h5 className="font-bold text-amber-700 dark:text-amber-400">Dynamic Timeout Growth under Standstill:</h5>
                <p className="leading-relaxed">
                  Notice how each validator's timeout value is growing exponentially: <code>Timeout = 1.2s &times; 1.05<sup>Missed</sup></code>. 
                  Because correct nodes are isolated and receive no finalization signatures, they raise their timeouts to survive network cuts. 
                  Once we trigger the **Megaphone Protocol** (after 10s), they will broadcast their highest finalized block states to unfreeze consensus!
                </p>
              </div>
            </div>
          )}

          {/* Real-time Logs */}
          <div className="space-y-2">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block">Simulator Event Logs</span>
            <div className="bg-slate-950 text-slate-300 p-4 rounded-lg font-mono text-xs overflow-y-auto h-44 border flex flex-col gap-1 text-left leading-relaxed">
              {simulationLogs.map((log, idx) => (
                <div key={idx} className="flex gap-2">
                  <span className="text-slate-500 font-sans">[{idx + 1}]</span>
                  <span>{log}</span>
                </div>
              ))}
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
